### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by mrskizzex** [majikat768/HuntStatsLogger#17]
Hey, i'm getting following error after launching the program again after few games logged. I'm attaching the hsl_files directory for you to troubleshoot, for now i just deleted the DB and it works again.

[hsl_files2.zip](https://github.com/majikat768/HuntStatsLogger/files/9954614/hsl_files2.zip)

```
PS C:\Users\XXX\Desktop\HuntStatsLogger> python src/main.py
qt.qpa.windows: setProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5  (E_ACCESSDENIED)
change detected
building json object
generating checksum
record exists
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\main.py", line 26, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\MainWindow\MainWindow.py", line 11, in __init__
    self.mainframe = MainFrame(self)
                     ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\MainWindow\MainFrame.py", line 52, in __init__
    self.update()
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\MainWindow\MainFrame.py", line 72, in update
    self.huntsTab.update()
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\MainWindow\Hunts\Hunts.py", line 137, in update
    self.updateDetails()
  File "C:\Users\XXX\Desktop\HuntStatsLogger\src\MainWindow\Hunts\Hunts.py", line 67, in updateDetails
    your_deaths[mmr] += d[0]
    ~~~~~~~~~~~^^^^^
KeyError: 6
QThread: Destroyed while thread is still running
PS C:\Users\XXX\Desktop\HuntStatsLogger>
```

**Comment by majikat768** [comment]
Ah I think I see what's going on...its supposed to tell your kill data based on the Star rating of the other player, but I think it's looking for stars 0 through 5, instead of 1 through 6.  So when you have a 6 star, it breaks. I'll fix that. Thanks!

**Comment by majikat768** [comment]
I fixed the error in the repository, so if you're running as a python script it should work now.  I'll upload the .exe with the fix later today.

**Comment by mrskizzex** [comment]
Thanks!
