### ISSUE TITLE
Can't start - neither script or installer

### ISSUE THREAD

**Issue by freedomfog** [majikat768/HuntStatsLogger#41]
I can't make it run!
No clue whats happening

Windows 11 pro, Python 3.11.0

[notice] To update, run: python.exe -m pip install --upgrade pip
launching app
qt.qpa.windows: setProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5  (Access denied.)
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::begin: Paint device returned engine == 0, type: 2
Traceback (most recent call last):
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\main.py", line 35, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainWindow.py", line 22, in __init__
    self.mainframe = MainFrame(self)
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainFrame.py", line 58, in __init__
    self.update()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainFrame.py", line 94, in update
    self.chartTab.update()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Chart\Chart.py", line 76, in update
    self.options[opt]()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Chart\Chart.py", line 101, in setMmr
    self.plot.getAxis("bottom").setTicks([[(i,str(i)) for i in range(0,xrange)]])
                                                               ^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

**Comment by freedomfog** [comment]
I think I "fixed" this by converting the float to int on this function on Char.py ln 101

from -> for i in range(0,xrange)]]) to -> for i in range(0,int(xrange))]])

but I'm not a Python programmer and I didn't have time to study the code, so I don't really know what is the impact of this change, the fact is that the xrange variable was a float of 6.0

**Comment by majikat768** [comment]
That is interesting, on my machine xrange is just an int 6...I'll take a look and see whats causing that, and try to get a fix out soon.
 Thanks!!

**Comment by freedomfog** [comment]
Thanks.
I could open the app and its kinda buggy... no team info etc. I restarted and now I got this error: 

PS C:\Users\Desktop\hunt\HuntStatsLogger-main> python ./src/main.py
launching app
qt.qpa.windows: setProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5  (Acesso negado.)
Traceback (most recent call last):
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\main.py", line 35, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainWindow.py", line 22, in __init__
    self.mainframe = MainFrame(self)
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainFrame.py", line 30, in __init__
    self.initBody()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\MainFrame.py", line 81, in initBody
    self.huntsTab = Hunts(parent=self)
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\Hunts.py", line 22, in __init__
    self.initUI()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\Hunts.py", line 37, in initUI
    self.update()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\Hunts.py", line 138, in update
    self.updateDetails()
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\Hunts.py", line 133, in updateDetails
    self.teamDetails.update(teams, hunters, hunt, killData,self.calculateMmrChange())
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\TeamDetails.py", line 159, in update
    hunterWidget = self.GetHunterWidget(teamhunters[j])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\hunt\HuntStatsLogger-main\src\MainWindow\Hunts\TeamDetails.py", line 276, in GetHunterWidget
    name = hunter['blood_line_nam']
           ~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'blood_line_nam'

**Comment by freedomfog** [comment]
I fixed again debugging and changing the attribute to blood_line_name.
Im using the main branch, I believe that's the problem?

**Comment by majikat768** [comment]
That's weird, I must have pushed a bug by mistake...I'll make some changes real quick and push those.  Thanks!

**Comment by majikat768** [comment]
Just pushed my most current version, which has been working fine for me, and added your change of casting xrange to int.

**Comment by freedomfog** [comment]
Oh I forgot to answer. Since this push everything worked fine!

**Comment by MechanicalKot** [comment]
Брат  у тебя чуть лёг софт я очень жду когда ты его починишь я верю в  тебя
