### ISSUE TITLE
Will not track matches

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#8]
Issue with latest release.

```
change detected
building json object
generating checksum
inserting record into database
insert_row
near "-": syntax error
D:/Steam/steamapps/common/Hunt Showdown\user/profiles/default/attributes.xml
mainframe.update
Traceback (most recent call last):
  File "D:\Hunt Stats Logger\HuntStatsLogger-0.3.2\src\MainWindow\MainFrame.py", line 54, in update
    self.huntsTab.update()
  File "D:\Hunt Stats Logger\HuntStatsLogger-0.3.2\src\MainWindow\Hunts\Hunts.py", line 54, in update
    self.updateDetails()
  File "D:\Hunt Stats Logger\HuntStatsLogger-0.3.2\src\MainWindow\Hunts\Hunts.py", line 42, in updateDetails
    hunt = GetHunt(ts)
  File "D:\Hunt Stats Logger\HuntStatsLogger-0.3.2\src\DbHandler.py", line 136, in GetHunt
    vals = execute_query("select * from 'games' where timestamp is %d" % ts)
TypeError: %d format: a real number is required, not NoneType
```

**Comment by majikat768** [comment]
Ahh, I think this was an issue with the previous version I had to fix as well...basically the data file has information on each boss with the variables "MissionBagBoss_0", "MissionBagBoss_1", "MissionBagBoss_2", "MissionBagBoss_3", corresponding to Spider, Assassin, Butcher, and Scrapbeak...but, for some people, there's also a "MissionBagBoss_-1", I don't know what it means, but the "-1" throws an error.  I think that should be a pretty easy fix

**Comment by majikat768** [comment]
updated the executable in the latest release, hopefully it should work now!

**Comment by JSKoenig** [comment]
Solved
